apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-v3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app
        version: v3
    spec:
      containers:
        - name: app
          image: "ashvarts/chop_demo:v3.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            
