apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    version: v2
spec:
  containers:
    - name: chop
      image: ashvarts/chop_demo:v2.0.0
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 5000
      resources:
        limits:
          cpu: 0.5
          memory: "256Mi"